---
- name: Configure BIND9
  hosts: all
  
  # tasks:
  #   - name: Ensure BIND9 is installed
  #     ansible.builtin.package:
  #       name: bind9
  #       state: present
      
  #   - name: Configure BIND9
  #     import_role:
  #       name: dubzland.bind9
